In [2]:
import numpy as np


In [18]:
filename = './USA-road-d.NY.co/USA-road-d.NY.co' # txt文件和当前脚本在同一目录下，所以不用写具体路径
Efield = []
x_list = []
y_list = []
with open(filename, 'r') as file_to_read:
    count = 0
    while True:
        item = []
        lines = file_to_read.readline() # 整行读取数据
        if not lines:
            break
        v, id, x_loc, y_loc = [i for i in lines.split()] # 将整行数据分割处理，如果分割符是空格，括号里就不用传入参数，如果是逗号， 则传入‘，'字符。
        item.append(int(id))  # 添加新读取的数据
        item.append(int(x_loc))
        item.append(int(y_loc))
        Efield.append(item)
        x_list.append(int(x_loc))
        y_list.append(int(y_loc))
        count += 1
"""         if count % 1000 == 0:
            print("count:",count)
            print("item:",item) """
city_show_num = 264346
x_list = np.array(x_list)[0:city_show_num]
y_list = np.array(y_list)[0:city_show_num]

city_co = np.array(Efield)
print(city_co)
print(x_list)

[[        1 -73530767  41085396]
 [        2 -73530538  41086098]
 [        3 -73519366  41048796]
 ...
 [   264344 -73820681  40994683]
 [   264345 -73714376  41004205]
 [   264346 -73917690  41291980]]
[-73530767 -73530538 -73519366 ... -73820681 -73714376 -73917690]


In [40]:
edge_show_num = 733846
F_list = np.random.randint(10,1000,edge_show_num) #费用
H_list = np.ones(edge_show_num,dtype=int) #限高
S_list = np.random.randint(10,150,edge_show_num) #限速
J_list = np.random.randint(1,6,edge_show_num) #1,2,3,4,5个拥堵等级
W_list = np.random.randint(1,4,edge_show_num) #1,2,3种天气

filename = './USA-road-d.NY.gr/USA-road-d.NY.gr' # txt文件和当前脚本在同一目录下，所以不用写具体路径
Efield = []
F_map = []
H_map = []
S_map = []
J_map = []
W_map = []
with open(filename, 'r') as file_to_read:
    count = 0
    while True:

        lines = file_to_read.readline() # 整行读取数据
        if not lines:
            break
        if count >= edge_show_num:
            break
        a, v_i, v_j, dis_ij = [i for i in lines.split()] # 将整行数据分割处理，如果分割符是空格，括号里就不用传入参数，如果是逗号， 则传入‘，'字符。
        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(int(dis_ij))
        Efield.append(item)

        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(F_list[count])
        F_map.append(item)

        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(H_list[count])
        H_map.append(item)

        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(S_list[count])
        S_map.append(item)

        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(J_list[count])
        J_map.append(item)

        item = []
        item.append(int(v_i))  # 添加新读取的数据
        item.append(int(v_j))
        item.append(W_list[count])
        W_map.append(item)

        count += 1
"""         if count % 1000 == 0:
            print("count:",count)
            print("item:",item)  """

dis_table = np.array(Efield)
F_map = np.array(F_map)
S_map = np.array(S_map)
print(dis_table)
#print(S_map)

[[     1      2    803]
 [     2      1    803]
 [     3      4    158]
 ...
 [263813 263466    106]
 [261228 259707    389]
 [259707 261228    389]]


In [25]:
F_list = np.random.randint(10,1000,city_show_num) #费用
print(F_list)

[655 554 937 ... 157 408 604]


In [41]:
# fee_map
with open('./multi_map/fee_map.txt', 'w') as handle:
    handle.writelines([
        "%d %d %d\n" % (item[0],item[1],item[2])
        for item in F_map
        ])

In [42]:
# H_map
with open('./multi_map/H_map.txt', 'w') as handle:
    handle.writelines([
        "%d %d %d\n" % (item[0],item[1],item[2])
        for item in H_map
        ])

In [43]:
# S_map
with open('./multi_map/S_map.txt', 'w') as handle:
    handle.writelines([
        "%d %d %d\n" % (item[0],item[1],item[2])
        for item in S_map
        ])

In [44]:
# J_map
with open('./multi_map/J_map.txt', 'w') as handle:
    handle.writelines([
        "%d %d %d\n" % (item[0],item[1],item[2])
        for item in J_map
        ])

In [45]:
# W_map
with open('./multi_map/W_map.txt', 'w') as handle:
    handle.writelines([
        "%d %d %d\n" % (item[0],item[1],item[2])
        for item in W_map
        ])